config/routes.rb
Rails.application.routes.draw do
  resources :daily_reports
  resources :mistakes
  resources :groups
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  root :to => "rails_admin/main#dashboard"
  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/daily_report.rb
class DailyReport < ApplicationRecord
  belongs_to :group
  belongs_to :user
  has_and_belongs_to_many :mistakes

  validates :date, presence: true
  validates :title, presence: true, length: {maximum: 50}
  validates :mistakes, presence: true
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true
end

app/models/mistake.rb
class Mistake < ApplicationRecord
  belongs_to :group
  validates :mistake_title, presence: true

  def name
    "#{mistake_title}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :groups

  validates :name, presence: true, length: {maximum: 50}, uniqueness: {case_sensitive: false}
  validates :email, presence: true, length: {maximum: 50}
  validates :password, presence: true
  validates :password_confirmation, presence: true

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/daily_reports_controller.rb
class DailyReportsController < ApplicationController
  before_action :set_daily_report, only: [:show, :edit, :update, :destroy]

  # GET /daily_reports
  # GET /daily_reports.json
  def index
    @daily_reports = DailyReport.all
  end

  # GET /daily_reports/1
  # GET /daily_reports/1.json
  def show
  end

  # GET /daily_reports/new
  def new
    @daily_report = DailyReport.new
  end

  # GET /daily_reports/1/edit
  def edit
  end

  # POST /daily_reports
  # POST /daily_reports.json
  def create
    @daily_report = DailyReport.new(daily_report_params)

    respond_to do |format|
      if @daily_report.save
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully created.' }
        format.json { render :show, status: :created, location: @daily_report }
      else
        format.html { render :new }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /daily_reports/1
  # PATCH/PUT /daily_reports/1.json
  def update
    respond_to do |format|
      if @daily_report.update(daily_report_params)
        format.html { redirect_to @daily_report, notice: 'Daily report was successfully updated.' }
        format.json { render :show, status: :ok, location: @daily_report }
      else
        format.html { render :edit }
        format.json { render json: @daily_report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /daily_reports/1
  # DELETE /daily_reports/1.json
  def destroy
    @daily_report.destroy
    respond_to do |format|
      format.html { redirect_to daily_reports_url, notice: 'Daily report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_daily_report
      @daily_report = DailyReport.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def daily_report_params
      params.require(:daily_report).permit(:title, :note, :group_id, :user_id, :mistake_id)
    end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name)
    end
end

app/controllers/mistakes_controller.rb
class MistakesController < ApplicationController
  before_action :set_mistake, only: [:show, :edit, :update, :destroy]

  # GET /mistakes
  # GET /mistakes.json
  def index
    @mistakes = Mistake.all
  end

  # GET /mistakes/1
  # GET /mistakes/1.json
  def show
  end

  # GET /mistakes/new
  def new
    @mistake = Mistake.new
  end

  # GET /mistakes/1/edit
  def edit
  end

  # POST /mistakes
  # POST /mistakes.json
  def create
    @mistake = Mistake.new(mistake_params)

    respond_to do |format|
      if @mistake.save
        format.html { redirect_to @mistake, notice: 'Mistake was successfully created.' }
        format.json { render :show, status: :created, location: @mistake }
      else
        format.html { render :new }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /mistakes/1
  # PATCH/PUT /mistakes/1.json
  def update
    respond_to do |format|
      if @mistake.update(mistake_params)
        format.html { redirect_to @mistake, notice: 'Mistake was successfully updated.' }
        format.json { render :show, status: :ok, location: @mistake }
      else
        format.html { render :edit }
        format.json { render json: @mistake.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /mistakes/1
  # DELETE /mistakes/1.json
  def destroy
    @mistake.destroy
    respond_to do |format|
      format.html { redirect_to mistakes_url, notice: 'Mistake was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_mistake
      @mistake = Mistake.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def mistake_params
      params.require(:mistake).permit(:mistake_title, :group_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/daily_reports_helper.rb
module DailyReportsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/mistakes_helper.rb
module MistakesHelper
end

app/views/daily_reports/_form.html.erb
<%= form_with(model: daily_report, local: true) do |form| %>
  <% if daily_report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(daily_report.errors.count, "error") %> prohibited this daily_report from being saved:</h2>

      <ul>
      <% daily_report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :note %>
    <%= form.text_area :note %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :mistake_id %>
    <%= form.text_field :mistake_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/daily_reports/edit.html.erb
<h1>Editing Daily Report</h1>

<%= render 'form', daily_report: @daily_report %>

<%= link_to 'Show', @daily_report %> |
<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Daily Reports</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Note</th>
      <th>Group</th>
      <th>User</th>
      <th>Mistake</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @daily_reports.each do |daily_report| %>
      <tr>
        <td><%= daily_report.title %></td>
        <td><%= daily_report.note %></td>
        <td><%= daily_report.group %></td>
        <td><%= daily_report.user %></td>
        <td><%= daily_report.mistakes %></td>
        <td><%= link_to 'Show', daily_report %></td>
        <td><%= link_to 'Edit', edit_daily_report_path(daily_report) %></td>
        <td><%= link_to 'Destroy', daily_report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Daily Report', new_daily_report_path %>

app/views/daily_reports/new.html.erb
<h1>New Daily Report</h1>

<%= render 'form', daily_report: @daily_report %>

<%= link_to 'Back', daily_reports_path %>

app/views/daily_reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @daily_report.title %>
</p>

<p>
  <strong>Note:</strong>
  <%= @daily_report.note %>
</p>

<p>
  <strong>Group:</strong>
  <%= @daily_report.group %>
</p>

<p>
  <strong>User:</strong>
  <%= @daily_report.user %>
</p>

<p>
  <strong>Mistake:</strong>
  <%= @daily_report.mistakes %>
</p>

<%= link_to 'Edit', edit_daily_report_path(@daily_report) %> |
<%= link_to 'Back', daily_reports_path %>

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Groups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @groups.each do |group| %>
      <tr>
        <td><%= group.name %></td>
        <td><%= link_to 'Show', group %></td>
        <td><%= link_to 'Edit', edit_group_path(group) %></td>
        <td><%= link_to 'Destroy', group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Group', new_group_path %>

app/views/groups/new.html.erb
<h1>New Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Back', groups_path %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @group.name %>
</p>

<%= link_to 'Edit', edit_group_path(@group) %> |
<%= link_to 'Back', groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quanlyduan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/mistakes/_form.html.erb
<%= form_with(model: mistake, local: true) do |form| %>
  <% if mistake.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(mistake.errors.count, "error") %> prohibited this mistake from being saved:</h2>

      <ul>
      <% mistake.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :mistake_title %>
    <%= form.text_field :mistake_title %>
  </div>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/mistakes/edit.html.erb
<h1>Editing Mistake</h1>

<%= render 'form', mistake: @mistake %>

<%= link_to 'Show', @mistake %> |
<%= link_to 'Back', mistakes_path %>

app/views/mistakes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Mistakes</h1>

<table>
  <thead>
    <tr>
      <th>Mistake title</th>
      <th>Group</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @mistakes.each do |mistake| %>
      <tr>
        <td><%= mistake.mistake_title %></td>
        <td><%= mistake.group %></td>
        <td><%= link_to 'Show', mistake %></td>
        <td><%= link_to 'Edit', edit_mistake_path(mistake) %></td>
        <td><%= link_to 'Destroy', mistake, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mistake', new_mistake_path %>

app/views/mistakes/new.html.erb
<h1>New Mistake</h1>

<%= render 'form', mistake: @mistake %>

<%= link_to 'Back', mistakes_path %>

app/views/mistakes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Mistake title:</strong>
  <%= @mistake.mistake_title %>
</p>

<p>
  <strong>Group:</strong>
  <%= @mistake.group %>
</p>

<%= link_to 'Edit', edit_mistake_path(@mistake) %> |
<%= link_to 'Back', mistakes_path %>